arch:
    max_epochs: 1
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 200.0
datasets:
    augmentation:
        image_shape: (384, 640)
    train:
        batch_size: 4
        dataset: ['DGP']
        path: ['/data/datasets/DDAD_tiny/ddad_tiny.json']
        split: ['train']
        depth_type: ['lidar']
        cameras: [['camera_01']]
        repeat: [500]
    validation:
        dataset: ['DGP']
        path: ['/data/datasets/DDAD_tiny/ddad_tiny.json']
        split: ['train']
        depth_type: ['lidar']
        cameras: [['camera_01']]
    test:
        dataset: ['DGP']
        path: ['/data/datasets/DDAD_tiny/ddad_tiny.json']
        split: ['train']
        depth_type: ['lidar']
        cameras: [['camera_01']]
