arch:
    validate_first: True
model:
    name: 'SemiSupCompletionModel'
    loss:
        supervised_method: 'sparse-silog'
        supervised_num_scales: 1
        supervised_loss_weight: 1.0
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNetSAN01'
        version: '1A'
        dropout: 0.5
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 200.0
        scale_output: 'resize'
datasets:
    augmentation:
        image_shape: (384, 640)
    train:
        batch_size: 1
        num_workers: 8
        dataset: ['DGP']
        path: ['/mnt/fsx/ddad_train_val/ddad.json']
        split: ['train']
        depth_type: ['lidar']
        cameras: [['camera_01'],['camera_05'],['camera_06'],['camera_09']]
        repeat: [5]
    validation:
        num_workers: 8
        dataset: ['DGP']
        path: ['/mnt/fsx/ddad_train_val/ddad.json']
        split: ['val']
        depth_type: ['lidar']
        input_depth_type: ['', '', '', '', 'lidar', 'lidar', 'lidar', 'lidar']
        cameras: [['camera_01'],['camera_05'],['camera_06'],['camera_09'],
                  ['camera_01'],['camera_05'],['camera_06'],['camera_09']]
    test:
        num_workers: 8
        dataset: ['DGP']
        path: ['/mnt/fsx/ddad_train_val/ddad.json']
        split: ['val']
        depth_type: ['lidar']
        cameras: [['camera_01']]
